[2024-04-08T09:04:44.012+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_with_taskflow_api_v02.greet manual__2024-04-08T09:04:42.984773+00:00 [queued]>
[2024-04-08T09:04:44.020+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_with_taskflow_api_v02.greet manual__2024-04-08T09:04:42.984773+00:00 [queued]>
[2024-04-08T09:04:44.021+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-04-08T09:04:44.021+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 6
[2024-04-08T09:04:44.021+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-04-08T09:04:44.035+0000] {taskinstance.py:1300} INFO - Executing <Task(_PythonDecoratedOperator): greet> on 2024-04-08 09:04:42.984773+00:00
[2024-04-08T09:04:44.040+0000] {standard_task_runner.py:55} INFO - Started process 10991 to run task
[2024-04-08T09:04:44.042+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_taskflow_api_v02', 'greet', 'manual__2024-04-08T09:04:42.984773+00:00', '--job-id', '1531', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_taskflow_api.py', '--cfg-path', '/tmp/tmpuc4aplia']
[2024-04-08T09:04:44.043+0000] {standard_task_runner.py:83} INFO - Job 1531: Subtask greet
[2024-04-08T09:04:44.093+0000] {task_command.py:388} INFO - Running <TaskInstance: dag_with_taskflow_api_v02.greet manual__2024-04-08T09:04:42.984773+00:00 [running]> on host 3dc1147ef06e
[2024-04-08T09:04:44.130+0000] {abstractoperator.py:613} ERROR - Exception rendering Jinja template for task 'greet', field 'op_kwargs'. Template: {'first_name': XComArg(<Task(_PythonDecoratedOperator): get_name>, 'first_naem'), 'last_name': XComArg(<Task(_PythonDecoratedOperator): get_name>, 'last_name'), 'age': XComArg(<Task(_PythonDecoratedOperator): get_age>)}
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 606, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 676, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 676, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 666, in render_template
    return value.resolve(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom_arg.py", line 342, in resolve
    raise XComNotFound(ti.dag_id, task_id, self.key)
airflow.exceptions.XComNotFound: XComArg result from get_name at dag_with_taskflow_api_v02 with key="first_naem" is not found!
[2024-04-08T09:04:44.139+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1374, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1493, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2115, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1179, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 606, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 676, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 676, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 666, in render_template
    return value.resolve(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom_arg.py", line 342, in resolve
    raise XComNotFound(ti.dag_id, task_id, self.key)
airflow.exceptions.XComNotFound: XComArg result from get_name at dag_with_taskflow_api_v02 with key="first_naem" is not found!
[2024-04-08T09:04:44.144+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_taskflow_api_v02, task_id=greet, execution_date=20240408T090442, start_date=20240408T090444, end_date=20240408T090444
[2024-04-08T09:04:44.154+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1531 for task greet (XComArg result from get_name at dag_with_taskflow_api_v02 with key="first_naem" is not found!; 10991)
[2024-04-08T09:04:44.174+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-04-08T09:04:44.189+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
