[2024-04-08T08:44:24.528+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: our_dag_with_python_operator_v06.greet manual__2024-04-08T08:44:22.895310+00:00 [queued]>
[2024-04-08T08:44:24.537+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: our_dag_with_python_operator_v06.greet manual__2024-04-08T08:44:22.895310+00:00 [queued]>
[2024-04-08T08:44:24.537+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-04-08T08:44:24.538+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 6
[2024-04-08T08:44:24.538+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-04-08T08:44:24.555+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): greet> on 2024-04-08 08:44:22.895310+00:00
[2024-04-08T08:44:24.561+0000] {standard_task_runner.py:55} INFO - Started process 8030 to run task
[2024-04-08T08:44:24.562+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'our_dag_with_python_operator_v06', 'greet', 'manual__2024-04-08T08:44:22.895310+00:00', '--job-id', '1521', '--raw', '--subdir', 'DAGS_FOLDER/create_dag_with_python_operator.py', '--cfg-path', '/tmp/tmps_uj_2c3']
[2024-04-08T08:44:24.564+0000] {standard_task_runner.py:83} INFO - Job 1521: Subtask greet
[2024-04-08T08:44:24.621+0000] {task_command.py:388} INFO - Running <TaskInstance: our_dag_with_python_operator_v06.greet manual__2024-04-08T08:44:22.895310+00:00 [running]> on host 3dc1147ef06e
[2024-04-08T08:44:24.683+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=jiseungmin
AIRFLOW_CTX_DAG_ID=our_dag_with_python_operator_v06
AIRFLOW_CTX_TASK_ID=greet
AIRFLOW_CTX_EXECUTION_DATE=2024-04-08T08:44:22.895310+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-04-08T08:44:22.895310+00:00
[2024-04-08T08:44:24.698+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/create_dag_with_python_operator.py", line 14, in greet
    age = ti.xcom_pull(task_id='get_age', key = 'age')
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
TypeError: xcom_pull() got an unexpected keyword argument 'task_id'
[2024-04-08T08:44:24.708+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=our_dag_with_python_operator_v06, task_id=greet, execution_date=20240408T084422, start_date=20240408T084424, end_date=20240408T084424
[2024-04-08T08:44:24.719+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1521 for task greet (xcom_pull() got an unexpected keyword argument 'task_id'; 8030)
[2024-04-08T08:44:24.735+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-04-08T08:44:24.750+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
